name: 'Security Scan'
description: 'An action to perform a security audit to identify vulnerabilities, secrets, and dependency issues.'

inputs:
  python-version:
    description: 'The Python version to use'
    required: true

  sync-extras:
    description: 'Extra dependencies'
    required: false
    default: 'production'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Setup Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install project dependencies
      run: |
        if [ -n "${{ inputs.sync-extras }}" ]; then
          for extra in ${{ inputs.sync-extras }}; do
            EXTRAS="$EXTRAS --extra $extra"
          done

          uv sync $EXTRAS
        else
          uv sync
        fi
      shell: bash

    - name: Install security tools
      run: uv tool install pip-audit
      shell: bash

    - name: Run pip-audit
      run: uv tool run pip-audit | tee pip_audit_report.txt
      shell: bash

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.4
      with:
        version: latest

    - name: Run Trivy
      run: trivy fs . --severity LOW,MEDIUM,HIGH,CRITICAL --format table | tee trivy_report.txt
      shell: bash

    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          pip_audit_report.txt
          trivy_report.txt
        retention-days: 7
